### ISSUE TITLE
Component Implementation - Document Alert

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#130]
## Description

This is a ticket to document the extracted Alert Box component from the mobile app.

## Important links

- [Current documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Flagship%20design%20library/Components/Alerts%20and%20Progress/AlertBox/)
- [Current primary code location](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/components/AlertBox.tsx)
- [Current primary test location](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/src/components/AlertBox.test.tsx)
- [npm package](https://www.npmjs.com/package/@department-of-veterans-affairs/mobile-component-library)
- [Component List](https://docs.google.com/spreadsheets/d/1_EAH2LWSzwF8Om7o4LAYJf6gT9UWENANYpF7SZy3j8w/edit#gid=106854297)

## Definition of Done

- [x] New Storybook stories published and working as expected
- [x] Storybook added to existing age on the docs site (created as part of 6745)
   - Will be handled by #112
- [x] A ticket has been created (and communicated to product) for the app teams to install the new component

**Comment by TimRoe** [comment]
Tickets created for flagship teams to implement:
- Health & Benefits: [8467](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8467)
- Global: [8468](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8468)
