### ISSUE TITLE
DS - Make Repo Public

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#141]
## Description 
As a gitHub user, I want to be able to see the va-mobile-library repo, so that I can see how the VA is building their mobile design system.

As part of this story we want to:   

- Make the va-mobile-library repo public to match other VA repos.

## Acceptance Criteria
  

-  [ ] Make the va-mobile-library repo public

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by narin** [comment]
Repo has been made public by https://github.com/department-of-veterans-affairs/github-user-requests/issues/19943#issuecomment-1967419029. Closing out.
