### ISSUE TITLE
BUG - Sev-3 - Web - Fix custom docs template

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-library#176]
## What happened?

We were previously using a custom docs template for Storybook to prepend a link to the documentation site. Upgrading to Storybook 7 broke this somewhat, because code snippets no longer worked when using a custom template. This might be fixable, but it might also be a Storybook bug.

## Steps to Reproduce

1. Re-add the following docs parameter to one of the component stories. e.g.
```
parameters: {
    docs: generateDocs({
      name: 'Button',
      docUrl:
        'https://department-of-veterans-affairs.github.io/va-mobile-app/design/Components/Buttons%20and%20links/Button',
    }),
  },
```
2. Load up storybook on web
3. Go to the Docs page for the modified story
4. Notice that "Show code" is disabled and says "No code available" 

## Desired behavior

We should be able to use a custom docs template with auto-generated code snippets

## Acceptance Criteria

- [ ] Fix the `generateDocs` util to display the auto-generated docs link
- [ ] Code snippets should work
- [ ] If unable to fix, create a bug on the storybook repo

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low

- 3 - Low

## Screen shot(s) and additional information

<img width="817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1pFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d98c159fe07ee043472e64141939f26405f5da40/image.png" alt="image.png" />

**Comment by bischoffa** [comment]
Unable to add severity label to this ticket. @narin  can you please add it
