### ISSUE TITLE
BUG - Sev 3 - Web - On press bolding does not work for Inline variant

### ISSUE THREAD

**Issue by TimRoe** [department-of-veterans-affairs/va-mobile-library#197]
## What happened?

When building the Link component Inline variant (#168), it was noted that the on press bolding does not work in Web Storybook. It works fine in iOS/Android. As Web is not an officially supported platform, this was deemed fine to separate.

## Steps to Reproduce

1. Navigate to the Directions Link variant in the [mobile design system storybook](https://department-of-veterans-affairs.github.io/va-mobile-library/?path=/story/link--directions)
2. Press and hold on the link
3. Note: It bolds the text while held
4. Navigate to the Inline Link variant
5. Press and hold one of the links
6. Note: It does not bold

## Desired behavior

Should bold on pressing like in iOS/Android.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

Web Storybook for demonstration purposes, not officially supported to function flawlessly.

- 3 - Low

## Linked to Story

Noted during #168 

## Screen shot(s) and additional information

Technically, the Inline variant uses React Native Text component instead of Pressable to wrap correctly so the links within Inline are built in a special way--this is likely the culprit. A fix to this bug may lie within the `react-native-web` package instead of any code we control based on it working in iOS/Android with the same code.

**Comment by bischoffa** [comment]
adding severity label to this ticket

**Comment by bischoffa** [comment]
Unable to add severity label to this ticket. @TimRoe can you please add it

**Comment by TimRoe** [comment]
I'll do you one better and close it entirely as on press bolding was determined to not be desired (after determining it was a miscommunication with VADS) and was replaced with on press background highlight. Also the inline Link variant no longer exists for now so it doubly doesn't exist.

Similar problem may occur with on press behavior of inline Links when it returns, but that may be quite some time and we can cross that bridge when we come to it again if it is problematic.
