### ISSUE TITLE
DS - Design Tokens: Create semantic tokens list based on VADS

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#238]
As a member of the DS team, I want to understand all of our semantic tokens and how they align with VADS, so that we can make informed decisions on token implementation.

**As part of this story, we want to:** 
- [x] Add our current tokens to the [spreadsheet](https://docs.google.com/spreadsheets/d/1v72J5g1T-dVoBqIhZ5EADlKc2IUscREdgaTvT7TGBDg/edit?usp=sharing)
     - [x] Loading indicator
     - [x] Alert
     - [x] Link
     - [x] Button
     - [x] Segmented control

- [x] Create list of missing tokens in variables.json file
- [x] Add missing tokens to VADS' variables.json file (Narin)

**Comment by jessicawoodin** [comment]
This ticket is waiting on a response from VADS (message sent on Tuesday 4/9).
