### ISSUE TITLE
BUG - Sev-3 - All - Link Icon is not vertically aligned at larger text sizes

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-library#240]
## What happened?

When zoomed in, Icons to the left of Links are not vertically aligned with the first line

Addition: Depending on when this is worked, a similar solution will also be needed on the Alert component which expects similar icon behavior and is initially copying Link's method.
- Moved addition to #246 as these changes were targeted as an escalated bug to be resolved for flagship implementation of the Link component

## Specs:

- Device: Any
- OS: Any

## Steps to Reproduce

1. Increase OS text size to largest size
2. View a Link with an Icon

## Desired behavior

Icon should be vertically centered and aligned with first line of text

## Acceptance Criteria

- [x] Icon is vertically centered and aligned with first line of text
   - [x] Icon remains vertically centered and aligned with first line of text even in the most extreme case of very large text + using preventScaling or maxWidth to keep the icon very small despite the very large text (see image in comments)

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 

- 3 - Low

## Screen shot(s) and additional information

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0RiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33e6cc63dc905715419d935a8e13736a3d6ccce2/image.png" alt="image.png" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)

**Comment by TimRoe** [comment]
Adding more extreme example of this bug (and added an AC for validation case) from flagship's implementation where they prevent scaling on the icon and it looks much worse with large font size:
![image](https://github.com/department-of-veterans-affairs/va-mobile-library/assets/8690976/7bb8a18d-425d-424c-9b6b-f394de7458c0)
