### ISSUE TITLE
DS - Loading Component Flagship Work Setup

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#250]
## Description 
This is a ticket for Product to create an epic and work with Flagship to plan the work.

### Notes
- The Sync screen is currently using a white variant of the LoadingIndicator which will not be available with the new version
- The app team has plans to redesign the login/sync screens with light/dark mode, so the LoadingIndicator should not be replaced on these screens until that work is complete
- If the app team would like to avoid linting warnings for this screen, they should delay updating the linting package to the latest version until all of the LoadingComponents have been replaced with LoadingIndicator

## Acceptance Criteria
  

-  [x]   Discuss with the team any specifics of implementing this component into the app
-  [x]   A ticket has been created (and communicated to product) for the app teams to install the new component

**Comment by narin** [comment]
Added comments regarding replacement of the LoadingIndicator on the login screens
