### ISSUE TITLE
BUG - Sev-3 - Storybook - Fix Code Snippets

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-library#261]
## What happened?

In Storybook, on each component's Docs page, it shows examples of each variant of our component. Previously, there was a button on the bottom right of each variant that would allow the user to see a code snippet of the implemented component. At some point (probably during the Storybook 7 upgrade, this broke and it now says 'No code available' instead. We want to fix this so that developers browsing our docs can see code examples.

## Specs:

- Device: Web
- OS: Web

## Steps to Reproduce

1. Go to the Docs page of any component (e.g. [Alert](https://department-of-veterans-affairs.github.io/va-mobile-library/?path=/docs/alert--docs))
2. Notice that each of the examples are showing 'No code available' on the bottom right

## Desired behavior

- Code snippets should be available

## Acceptance Criteria

- [ ] Fix the display of code snippets in Storybook

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: High

- 3 - Low

## Screen shot(s) and additional information

![image](https://github.com/department-of-veterans-affairs/va-mobile-library/assets/786704/5ffbd35d-29d6-4e83-b440-680321c8b543)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)

**Comment by bischoffa** [comment]
Unable to add severity label to this ticket. @narin can you please add it
