### ISSUE TITLE
Jest Matchers - Enhance Accessibility Unit Tests

### ISSUE THREAD

**Issue by TimRoe** [department-of-veterans-affairs/va-mobile-library#279]
## Description 
Split from #134.

It was discovered during #134 that a more proper way of testing the a11yValue override was available using [Jest Matchers](https://callstack.github.io/react-native-testing-library/docs/jest-matchers), but it appeared to require additional Jest configuration that was not already setup and our configuration didn't readily match up to the Jest [guidance for adding Jest Matchers](https://callstack.github.io/react-native-testing-library/docs/getting-started#jest-matchers). Since it was discovered mostly after getting the accessibility tests to work somewhat correctly via brute force, this ticket was split off to handle the necessary Jest configuration changes to enable this more proper way of validating the accessibility (and other helpful additions to the standard data matching Jest offers).

## Acceptance Criteria
  

-  [ ] Update Jest configuration to leverage the enhanced Jest Matchers
-  [ ] Fix any linting errors associated with new eslint extension
-  [ ] Update the `a11y tests` set of Link and Alert tests with the improved Jest Matcher for a11yValue
-  [ ] If possible, also improve the a11y-Label/Hint to actually read values instead of just checking prop values

**Comment by narin** [comment]
Tried to add Jest matchers for Alert accessibility tests and found that the new eslint plugin would require changes to all of our unit tests. Adjusted this AC to account for that, renamed ticket, and bumped estimate to 8 points.

CC: @kellylein
