### ISSUE TITLE
DS - Replace VA Logo and service emblems SVGs with PNGs. Add Space Force and VA dark text logo

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#304]
## Description 
As a design system user, I want to be able to use the latest VA and USSF logos in my designs, so that my designs can be as accurate as possible.

## Acceptance Criteria

-  [ ] Add VA logo and service emblems to assets package in image format
-  [ ] Remove existing .svg files for VA logo and service emblems from assets package
-  [ ] Remove VA logo and service emblems from Icon component
-  [ ] Let @jessicawoodin know when this is complete, so she can update Figma.

## Logos (PNGs)
[Logos.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXYxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51772cc8015fb2a9da453afb28778fa5f2fc1ad1/Logos.zip)
[Emblems.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0g5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--188c86e875aba2511ecf7e70607e61c663cb448b/Emblems.zip)

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by narin** [comment]
Updated AC to reflect transition from SVGs to images for logos and service emblems. Thread here: https://adhoc.slack.com/archives/C05DQPHUVNZ/p1715951376378689
