### ISSUE TITLE
DS - Loading Component Test Plan

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#310]
## Description 
As a QA, I want to understand the Loading Component, so that I can prepare my test plan.

As part of this story we want to:   

- Learn about the Loading Component so I know how best to test it once it is ready.

## Acceptance Criteria
  

-  [ ] Ensure Storybook is set up for testing
-  [ ] Create Test Plan for the Loading Component

**Comment by kellylein** [comment]
@DJUltraTom this one can be pulled in whenever you are ready.

**Comment by kellylein** [comment]
@DJUltraTom any updates on this ticket?

**Comment by DJUltraTom** [comment]
We can utilize existing test cases, and pull the relevant ones into a standard test run to validate the screens where the component is displaying. documenting relevant cases in this comment so there is an easy source to pull from for the test run. (versus digging through the cases in testrail's assign window)

This is a very high level case but may suffice as a standalone test to verify all of these areas are displaying the spinner correctly and with the correct copy: https://dsvavsp.testrail.io/index.php?/cases/view/13605&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=3504

More specific test cases if we feel the need to test more granularly:
https://dsvavsp.testrail.io/index.php?/cases/view/13229
https://dsvavsp.testrail.io/index.php?/cases/view/13357
https://dsvavsp.testrail.io/index.php?/cases/view/13387
https://dsvavsp.testrail.io/index.php?/cases/view/13455
https://dsvavsp.testrail.io/index.php?/cases/view/13486
https://dsvavsp.testrail.io/index.php?/cases/view/13523
https://dsvavsp.testrail.io/index.php?/cases/view/13562
https://dsvavsp.testrail.io/index.php?/cases/view/13588
https://dsvavsp.testrail.io/index.php?/cases/view/13646
https://dsvavsp.testrail.io/index.php?/cases/view/13732
https://dsvavsp.testrail.io/index.php?/cases/view/13733
https://dsvavsp.testrail.io/index.php?/cases/view/31934
https://dsvavsp.testrail.io/index.php?/cases/view/31760
https://dsvavsp.testrail.io/index.php?/cases/view/32105
https://dsvavsp.testrail.io/index.php?/cases/view/20770
https://dsvavsp.testrail.io/index.php?/cases/view/35520
https://dsvavsp.testrail.io/index.php?/cases/view/59279
*some of these cases are very old and may need additional review.

**Comment by DJUltraTom** [comment]
@kellylein do we know if [This spreadsheet](https://docs.google.com/spreadsheets/d/1vSpeZj0c1V_OnQZTp3FolyUb_H0H66z4ETXJLUXjxKs/edit?gid=0#gid=0) is still a valid source of truth for text on the loading component pages?

**Comment by DJUltraTom** [comment]
current high level test plan (in progress) [here](https://dsvavsp.testrail.io/index.php?/cases/view/86394)

**Comment by DJUltraTom** [comment]
Updated the test plan linked above, @rbontrager could I get you to review it when you have a chance?

**Comment by rbontrager** [comment]
@DJUltraTom Found a couple things.

You are missing the following features loading screens:
Claims > Claims history
Claims > Claims letters or
Claims > Closed > Claim with decision letters > Get claim letter
VA Letters and Docs > Review letters > Benefit summary and service verification letter 
Prescriptions > prescription details
Prescriptions > prescription details with refill > request refill or
Prescriptions > start refill request > select a prescription > request refills
Prescriptions
Prescriptions > start refill request
Prescriptions > prescription with tracking > get prescription tracking
Messages > message with reply > reply
Home > profile > contact info
Home > profile > military info
Home > profile > personal info
Home > profile > personal info > gender identity
Home > profile > personal info > preferred name

And the navigation in the steps for the following features are wrong: Disability rating, Home/Mailing Address, Home/Work/Cell Phone, Direct Deposit, Letters, and Payments

**Comment by DJUltraTom** [comment]
updated the test case based on @rbontrager 's feedback
Test case hits all instances of the loading spinner, which would be great if we are able to automate, but likely unnecessary and a manual spot check will suffice.

**Comment by DJUltraTom** [comment]
closing, but there is no "closed" label
