### ISSUE TITLE
DS - Loading Indicator Functional QA

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#311]
## Description 
As a member of the Flagship team, I want to feel confident that new components are bug-free, so that it is easier for me to incorporate them into the app.

As part of this story we want to:   

- ensure the Loading Component is functioning as expected
- work with Jessica to ensure both Visual and Functional QA is covered

## Acceptance Criteria
  

-  [ ] test the Loading Indicator component in Storybook
-  [ ] ensure analytics are setup (via console log)

**Comment by DJUltraTom** [comment]
When the component is ready to be tested follow: https://dsvavsp.testrail.io/index.php?/cases/view/86394
likely only a manual spot check will be required,

**Comment by bischoffa** [comment]
@DJUltraTom is this ready to be worked its in the current sprint column but not tagged to the current sprint? Plus from your comment it seems this needs to be moved to the backlog of blocked if work is not ready yet for you to do this. 

Can you update the ticket accordingly?

**Comment by DJUltraTom** [comment]
Moving to blocked until the following tickets are in process and at a point to be tested:
[8937](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8937)
[8936](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8936)

Reiterating for when QA is ready to occur, [This Test Plan](https://dsvavsp.testrail.io/index.php?/cases/view/86394) should cover every part of the app where the loading indicator should appear. We will likely only need to spot check this, especially if an automated solution is available. As this component has no associated analytics no tracking QA needs to occur.

**Comment by kellylein** [comment]
This Story is to QA the component outside the context of the app.  This testing would be done primarily in Storybook, which is available.

**Comment by DJUltraTom** [comment]
not blocked as this is for Design testing not FE implementation. closing

**Comment by bischoffa** [comment]
@DJUltraTom any findings from the storybook testing? Or is that under a different ticket.
