### ISSUE TITLE
[Design System] Assets: Update logos and emblems in flagship mobile app

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-library#341]
### What was updated in the Design System?
In **va-mobile-library**, the official VA logos and emblems were updated in version 0.6.0 of the [Assets package](https://github.com/department-of-veterans-affairs/va-mobile-library/tree/main/packages/assets) and [Figma library](https://www.figma.com/design/X8gXRl1MaRAE7lKcwgr5Rj/%F0%9F%93%90-Icon-Library---Design-System---VA-Mobile?node-id=212-1739) to be consistent with VA.gov. The new files are:
- [VALogo](https://github.com/department-of-veterans-affairs/va-mobile-library/tree/main/packages/assets/VALogo)
     - VAOnDark.png
     - VAOnLight.png
- [serviceEmblems](https://github.com/department-of-veterans-affairs/va-mobile-library/tree/main/packages/assets/serviceEmblems)
     - vic-air-force-coat-of-arms.png
     - vic-army-symbol.png
     - vic-cg-emblem.png
     - vic-navy-emblem.png
     - vic-space-force-logo-on-dark.png
     - vic-space-force-logo-on-light.png
     - vic-space-force-logo.png
     - vic-usmc-emblem.png

### What changes are recommended in the Flagship Mobile App?
1. In **va-mobile-app**, the VA logos and emblems in the [VAIcon component](https://github.com/department-of-veterans-affairs/va-mobile-app/tree/develop/VAMobile/src/components/VAIcon) should be updated as follows. After the files are updated, the [vaParentLogo](https://github.com/department-of-veterans-affairs/va-mobile-app/tree/develop/VAMobile/src/components/VAIcon/svgs/vaParentLogo) and [dodBranch](https://github.com/department-of-veterans-affairs/va-mobile-app/tree/develop/VAMobile/src/components/VAIcon/svgs/dodBranch) files should be removed from the VAIcon component.
     - **Update**: Logo.svg :arrow_right: VAOnDark.png
     - **Update**: AirForce.svg :arrow_right: vic-air-force-coat-of-arms.png
     - **Update**: Army.svg :arrow_right: vic-army-symbol.png
     - **Update**: CoastGuard.svg :arrow_right: vic-cg-emblem.png
     - **Update**: MarineCorps.svg :arrow_right: vic-usmc-emblem.png
     - **Update**: Navy.svg :arrow_right: vic-navy-emblem.png
     - **New**: VAOnLight.png
     - **New**: vic-space-force-logo-on-dark.png
     - **New**:  vic-space-force-logo-on-light.png
     - **New**: vic-space-force-logo.png
2. In **Figma**, the VA logos and emblems should be updated in the shipped files. After the files are updated, the Logo component should be removed from the Flagship Library file.

### Where are these files used in the Flagship Mobile App?
Currently, the logos and service emblems are used on the home screen, profile screen, and Veteran Status.

## Additional resources
- [How to use the Assets package](https://department-of-veterans-affairs.github.io/va-mobile-app/design/About/For%20engineers/assets)
- Documentation on Logos will be available in the coming weeks
- For more information about Service Emblems, reach out to #va-mobile-design-system in Slack.

## Acceptance criteria
- [ ] Logos and emblems are updated in va-mobile-app with the files in va-mobile-library's Assets package
- [ ] Logos and emblems are removed from VAIcon component in va-mobile-app
- [ ] Logos and emblems are updated in shipped files in Figma.
- [ ] Logos and emblems are removed from the Flagship Library file in Figma.

**Comment by kellylein** [comment]
Closing in favor of the same thing in an Epic ticket: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8784
