### ISSUE TITLE
DS -  SnackBar Global typescript declaration

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-library#412]
## Description
Unlike other components, we are making the snackbar available globally to mimic how it is ued in the app. This requires some TypeScript configuration in order to not throw errors. Without the proper configuration, it may throw errors similar to this:

```
node_modules/@department-of-veterans-affairs/mobile-component-library/src/components/Snackbar/Snackbar.tsx(57,34): error TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature. 
error Command failed with exit code 2.
```

```[tasklist]
### Acceptance Criteria
- [ ] `// @ts-nocheck` is removed from `Snackbar.tsx`
- [ ] Snackbar global var is configured properly
- [ ] Testing in the mobile app does not throw any TS errors related to Snackbar
```

**Comment by TimRoe** [comment]
Closing this ticket as no longer relevant from #415 and PR #423 making the Snackbar now using wrapper/hook instead of global implementation.
