### ISSUE TITLE
DS - Checkbox Group Component Analytics Support

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#429]
As an owner of the app, I want to have access to the interaction analytics of the Checkbox Group component, so that I can make data-based decisions.

As part of this story we want to allow the Checkbox Group to pass analytics data to the app

#Acceptance Criteria
- [ ] Determine if analytics are needed
- [ ] Add function passthroughs for apps to be able to log analytics based on interactions handled by the Checkbox Group component

**Comment by narin** [comment]
Analytics should be covered by the `onPress` for Checkbox and `onSelectionChange` for CheckboxGroup. Closing this ticket out.
