### ISSUE TITLE
DS - Checkbox Group Component Flagship Work Setup

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#433]
## Description 
This is a ticket for Product to create an epic and work with Flagship to plan the work.

### Notes
- Global: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9967
- H&B: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9966

## Acceptance Criteria
  

-  [x]   A ticket has been created for the app teams to install the new component
-  [x]   Dev adds implementation details to ticket
-  [x]   UX adds design implementation details to ticket

**Comment by kellylein** [comment]
The Flagship Epics are ready to add any design and technical details to help aide implementation.

**Comment by narin** [comment]
Updated both epics with additional engineering implementation notes
