### ISSUE TITLE
DS - Typography Tokens - Create Composite Tokens

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#495]
## Description 
As part of this story, we want to:
- Create 10 composite tokens (styles) from individual typography tokens.
- Revisit portions split from #494 (see ACs)

## Design Notes
- [Spreadsheet with all tokens](https://docs.google.com/spreadsheets/d/1v72J5g1T-dVoBqIhZ5EADlKc2IUscREdgaTvT7TGBDg/edit?gid=893658788#gid=893658788)
     - This spreadsheet has each composite token (style) on its own row with columns for each individual token (family, style, size, etc.)
     - I was unsure how a composite token would be named in React Native, so I included a Style Name and Composite Token Name.
     - Even though paragraph spacing will not be included in React Native, I included it in this spreadsheet for reference.
- [Visual reference in Figma](https://www.figma.com/design/XQwpzcNSGyGJN4nXDPoEj0/Design-Tokens---%F0%9F%94%8D-Design-System---VA-Mobile?node-id=344-11233&t=DVF9GkofQ7yStw0e-4)
     - In Figma, all line heights are rounded to 1 decimal point and all paragraph spacings are rounded to 2 decimal points. In the code, we'd like to keep 2 decimal points for all values.
<img width="963" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFh3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6129e2d33a5d9038eb58d7de24ba901ca31d40db/image.png" alt="image.png" />

## Acceptance Criteria
- [ ] Create 10 composite tokens (styles) from individual typography tokens
- [ ] Update assets package and storybook config to incorporate Bitter-Regular font capability and remove Bitter-Bold font capability

## Ticket Checklist
- [ ] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by narin** [comment]
Removed the following AC as it was confirmed that Figma doesn't support composite tokens:
- Split from #494 
   - [ ] Explore grouping font tokens in the Figma export as part of this effort
      - Split out due to additional complexity since as of that ticket there was only 1:1 alignment of tokens in to tokens out and it didn't contain any logic for forming groups of unknown counts of tokens which necessarily involves cross-token interaction to appropriately start/close each grouping in valid JSON
      - Experimented with various solutions on 494, but none panned out and was hoping to avoid brute forcing it by manually building the JSON groups via strings and continuing to rely on manipulating the tokens holistically via the reducer or another structure
      - If the composite tokens for this ticket still don't yield a better method for addressing grouping tokens, split out to another ticket to explore further or implement the brute force method of building the JSON with strings
