### ISSUE TITLE
Feature - Automate Syncing Tokens to Figma

### ISSUE THREAD

**Issue by TimRoe** [department-of-veterans-affairs/va-mobile-library#52]
## Description
Effectively a clone ticket of [7366](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7366) for if the barriers preventing the preferred/middling outcomes from being possible are resolved. Configuring the automation currently requires an Enterprise Figma license leaving either two options to be able to move forward:
1. Figma changes their mind and opens access to Variables scopes with a lesser license as they progress from beta stages
2. If/when moving to VA Figma if they have Enterprise licenses

If these barriers are lifted, the goal is the same as that prior ticket. [Both](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7366#issuecomment-1836515946) of the [comments](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7366#issuecomment-1856272258) on ticket 7366 will likely be helpful for working this ticket if/when it can be.

## Cloned Details from 7366
As a follow-up to #6860, this ticket is to explore options to automate the process. This would be ideal since currently ~~there is some small effort on engineers to ensure any changes get propagated to the repo (running `yarn build` after final changes on a branch prior to merging main)~~ [resolved by 7366] and effort for designers to keep Figma synced as it needs to be manually done each time changes occur [pulling from the repo folder](https://github.com/department-of-veterans-affairs/va-mobile-library/tree/main/packages/tokens/figma). While neither lift is huge, it introduces multiple opportunities for Figma to fall out of alignment with the code which is precisely what we want to avoid.

Late in the process of that ticket it was noted that [the Variables section of the Figma doc](https://www.figma.com/developers/api#variables) includes [a REST API](https://www.figma.com/developers/api#post-variables-endpoint) that theoretically should allow automation as noted in [this Figma community file](https://www.figma.com/community/file/1270821372236564565) which includes [a FigJam that details (right column)](https://www.figma.com/file/zTTaZVOqVAVY159Hi8Mw4B/Syncing-design-systems-using-Variables-REST-API-(Community)?type=whiteboard&node-id=0-1&t=ZBiOyL2stkfn1Yhm-0) on how you should be able to configure GHA to automatically propagate from a repo into Figma.

One concern Jessica expressed discussing the possibility to look into as part of this is:
> My one concern with it updating automatically is not being able to preview any of the changes and revert it in the version history if anything was broken. Currently, we'd use branching to update anything in the design library. If/when you look into automating it, can you see what the options might be for previewing/branching the automated updates?

At a glance, it sounds feasible to create a new "collection" each time the API posts which hopefully will allow stacking up new versions without getting rid of the history for older versions.

Assuming the above all pans out, great! If it doesn't, ~~at the very least this ticket should implement a GHA to square away the gap in the engineer flow by automating ensuring the latest changes committed to `main` update the `figma` folder (and, ideally, does not leave the `dist` folder in the repo so it only runs the `figma` build with style-dictionary).~~ [resolved by 7366]

## Acceptance Criteria
  
In priority order, discard less preferred outcomes if better ones accomplished:

-  [ ] Preferred outcome: We can follow Figma's guides to use the API to automatically sync tokens on merge to `main` so they are immediately updated in Figma and in a way that respects Figma versioning history and branching structure design is leveraging
-  [ ] Middling outcome: We can mostly achieve the preferred outcome, but need to compromise some to play nice with structure
-  [x] ~~Minimal outcome: We can't automate the workflow into Figma. At least close the loop on the engineer side by automating building the `figma` folder in the repo, ideally without the `dist` folder lingering in the repo~~ [resolved by 7366]

**Comment by kellylein** [comment]
We don't see this as being needed now.
