### ISSUE TITLE
[Design Tokens] Colors: Add new feedback tokens to VADS

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-library#541]
We're adding new feedback-related foreground tokens to the system and need 2 new primitive and 2 new semantic tokens added to VADS.

- [x] Add 4 new tokens to VADS
     - Primitive
          - uswds-system-color-green-cool-vivid-30
          - uswds-system-color-gold-vivid-40
 
     - Semantic
          - vads-color-feedback-foregound-success-on-dark: uswds-system-color-green-cool-vivid-30
          - vads-color-feedback-foregound-warning-on-light: uswds-system-color-gold-vivid-40
          - vads-color-feedback-foregound-success-on-light: uswds-system-color-green-cool-vivid-50
          - vads-color-feedback-foregound-warning-on-dark: uswds-system-color-gold-vivid-30
- [x] After tokens are available in variables.json file, make sure tokens are available in va-mobile-library.
- [x] Let Jessica know when they're available and she will add the tokens in Figma.

**Comment by narin** [comment]
PR in VADS repo created: https://github.com/department-of-veterans-affairs/component-library/pull/1417

[Slack thread](https://dsva.slack.com/archives/C06D8NB8R8V/p1732125668199349)
