### ISSUE TITLE
DS - Text Component Accessibility Review

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#551]
## Description 
As part of this story we want to:   

- Once the Typography component is available in Storybook, Brea will complete an accessibility review and create tickets for any additional work.

## Acceptance Criteria
  

-  [x] Review component for and accessibility issues
-  [x] Create Bug tickets for any changes needed

## Accessibility Audit Checklist
- [x] Verify that the component scales with increased font sizes and with display zoom enabled.
- [x] Verify that the component passes color contrast minimums.
- [x] Verify that no screenreader issues exist.
- [x] Verify that the component works with a keyboard and that there are no keyboard traps.
- [x] Verify that the component works with Voice Access / Switch Control.
- [x] Verify that the overall structure is accessible (headings are properly labeled, etc.).
- [x] Verify that any error messaging displays properly / as expected.
- [x] Verify that any tappable areas (links, buttons, etc.) meet target size minimums.

**Comment by brea11y** [comment]
@kellylein – I just saw that this was moved to "in progress". Just want to confirm that this is ready for the accessibility review?

**Comment by brea11y** [comment]
No accessibility issues found! Y'all did an excellent job on this!
