### ISSUE TITLE
DS - Text Component Analytics Support

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#553]
As an owner of the app, I want to have access to the interaction analytics of the Typography component, so that I can make data-based decisions.

As part of this story we want to allow the Typography component to pass analytics data to the app if applicable

#Acceptance Criteria
- [x] Determine if analytics are needed
- [ ] Add function passthroughs for apps to be able to log analytics based on interactions handled by the component

**Comment by narin** [comment]
Analytics are not needed for this component since there is no interaction expected. Closing out.
