### ISSUE TITLE
DS - Design Tokens - Spacing

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-library#80]
# Project Status Overview

### Project Objective:

- Create design tokens for common spacing used within the app.  This will allow greater consistency throughout the app and flexibility when doing global spacing updates.

### Monthly Update for Stakeholders

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|8/20/24 | Determined that Typography tokens will utilize some Spacing tokens, so we have started on Spacing tokens along with Typography tokens. | none |
|9/3/24 |  Updating Spacer component to utilize spacing tokens  | None |
|10/1/24 |  Wrapping up final documentation this Sprint  | None |

**Comment by kellylein** [comment]
Q3 SWAG:
UX - 2
FE - 1.5 sprints

**Comment by jessicawoodin** [comment]
Design notes for the spacing tokens, spacer component, and JSON file can be found in this [Figma working file](https://www.figma.com/design/XQwpzcNSGyGJN4nXDPoEj0/Design-Tokens---%F0%9F%94%8D-Design-System---VA-Mobile?node-id=224-11204).

Additional notes can also be found in this [Google Doc](https://docs.google.com/document/d/1IxQ63s0EEjR_oKG_9Jyqk9hqy9isLazYsi2SpHSJb8Y/edit?tab=t.0#heading=h.66qzle3qg4wa). All spacing tokens will be added to this [spreadsheet](https://docs.google.com/spreadsheets/d/1v72J5g1T-dVoBqIhZ5EADlKc2IUscREdgaTvT7TGBDg/edit?gid=339112386#gid=339112386).

**Comment by kellylein** [comment]
Flagship app implementation Epics: [#9751](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-library/9751), [#9750](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-library/9750)
